// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using my_new_app.Models;

namespace mynewapp.Migrations
{
    [DbContext(typeof(NewBoilerPlateDBContext))]
    [Migration("20190611075711_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("my_new_app.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("my_new_app.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<int>("Price");

                    b.HasKey("Id");

                    b.ToTable("product");
                });

            modelBuilder.Entity("my_new_app.Models.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustId")
                        .HasColumnName("custId");

                    b.Property<DateTime?>("Datesold")
                        .HasColumnName("datesold")
                        .HasColumnType("datetime");

                    b.Property<int?>("ProdId")
                        .HasColumnName("prodId");

                    b.Property<int?>("StoreId")
                        .HasColumnName("storeId");

                    b.HasKey("Id");

                    b.HasIndex("CustId");

                    b.HasIndex("ProdId");

                    b.HasIndex("StoreId");

                    b.ToTable("sales");
                });

            modelBuilder.Entity("my_new_app.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("store");
                });

            modelBuilder.Entity("my_new_app.Models.Sales", b =>
                {
                    b.HasOne("my_new_app.Models.Customer", "Cust")
                        .WithMany("Sales")
                        .HasForeignKey("CustId")
                        .HasConstraintName("FK__sales__custId__0DAF0CB0");

                    b.HasOne("my_new_app.Models.Product", "Prod")
                        .WithMany("Sales")
                        .HasForeignKey("ProdId")
                        .HasConstraintName("FK__sales__prodId__0CBAE877");

                    b.HasOne("my_new_app.Models.Store", "Store")
                        .WithMany("Sales")
                        .HasForeignKey("StoreId")
                        .HasConstraintName("FK__sales__storeId__0EA330E9");
                });
#pragma warning restore 612, 618
        }
    }
}
